name: Publish Releases

on: 
  push:
    tags: 
      - 'v*'

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install requirements
        run: |
            python -m pip install --upgrade pip
            pip install twine

      - name: Build dists
        run: |
          python setup.py sdist

      - name: Publish package
        env:
          TWINE_REPOSITORY: pypi
          TWINE_NON_INTERACTIVE: true
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/* 
